/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IBerachainRewardsVault } from "./IBerachainRewardsVault";
export type { IBerachainRewardsVaultFactory } from "./IBerachainRewardsVaultFactory";
export type { Passes } from "./Passes";
export type { PassesStakingToken } from "./PassesStakingToken";
