/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IBerachainRewardsVaultFactory,
  IBerachainRewardsVaultFactoryInterface,
} from "../../../../contracts/mocks/MockPasses.sol/IBerachainRewardsVaultFactory";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "stakingToken",
        type: "address",
      },
    ],
    name: "createRewardsVault",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IBerachainRewardsVaultFactory__factory {
  static readonly abi = _abi;
  static createInterface(): IBerachainRewardsVaultFactoryInterface {
    return new Interface(_abi) as IBerachainRewardsVaultFactoryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IBerachainRewardsVaultFactory {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IBerachainRewardsVaultFactory;
  }
}
