/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IBerachainRewardsVault__factory } from "./IBerachainRewardsVault__factory";
export { IBerachainRewardsVaultFactory__factory } from "./IBerachainRewardsVaultFactory__factory";
export { MockPasses__factory } from "./MockPasses__factory";
export { PassesStakingToken__factory } from "./PassesStakingToken__factory";
