/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as mockBerachainRewardsVaultFactorySol from "./MockBerachainRewardsVaultFactory.sol";
export type { mockBerachainRewardsVaultFactorySol };
import type * as mockPassesSol from "./MockPasses.sol";
export type { mockPassesSol };
