/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as mockBerachainRewardsVaultFactorySol from "./MockBerachainRewardsVaultFactory.sol";
export * as mockPassesSol from "./MockPasses.sol";
