/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IBerachainRewardsVault } from "./IBerachainRewardsVault";
export type { MockBerachainRewardsVault } from "./MockBerachainRewardsVault";
export type { MockBerachainRewardsVaultFactory } from "./MockBerachainRewardsVaultFactory";
