/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../common";
import type {
  MockBerachainRewardsVault,
  MockBerachainRewardsVaultInterface,
} from "../../../../contracts/mocks/MockBerachainRewardsVaultFactory.sol/MockBerachainRewardsVault";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "delegateStake",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "delegateWithdraw",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x60808060405234601457608c908161001a8239f35b600080fdfe60806040526004361015601157600080fd5b60003560e01c80633c323a1b14602f57635281244f14602f57600080fd5b3460515760403660031901126051576004356001600160a01b03811603605157005b600080fdfea26469706673582212209c803df7dccec29eba9153ddde95d3294535ad624069ba7342ce65d41af5ae6c64736f6c63430008140033";

type MockBerachainRewardsVaultConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MockBerachainRewardsVaultConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MockBerachainRewardsVault__factory extends ContractFactory {
  constructor(...args: MockBerachainRewardsVaultConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      MockBerachainRewardsVault & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(
    runner: ContractRunner | null
  ): MockBerachainRewardsVault__factory {
    return super.connect(runner) as MockBerachainRewardsVault__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MockBerachainRewardsVaultInterface {
    return new Interface(_abi) as MockBerachainRewardsVaultInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): MockBerachainRewardsVault {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as MockBerachainRewardsVault;
  }
}
