/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as passesSol from "./Passes.sol";
export * as mocks from "./mocks";
export { ICustomBerachainRewardsVault__factory } from "./ICustomBerachainRewardsVault__factory";
