/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as passesSol from "./Passes.sol";
export type { passesSol };
import type * as mocks from "./mocks";
export type { mocks };
export type { ICustomBerachainRewardsVault } from "./ICustomBerachainRewardsVault";
